baseurl: http://blog.10pines.com/
disablePathToLower: true
languageCode: en-us
title: "10 Pines Blog"
theme: "hugo-theme-bleak"
params:
  cover: "/images/10pines-background.jpg"
  Subtitle: "We don't just write code. We craft your ideas"
  logo: "/images/10p-logo.png"
# paginate: 9
# copyright: "© 2009 Copyright Text"
#
# params:
#   description: "Your Site Description" # optional
#   twitter: "Your Twitter Name" # optional
#   gitlab: "Your Gitlab Name" # optional
#   github: "Your Github Name" # optional
#   facebook: "Your facebook Name" # optional
#   gplus: "Your Google+ profile name" # optional
#   linkedin: "Your LinkedIn Name" # optional
#   headerCover: "images/10pines-background.jpg" # optional
#   footerCover: "images/10p-logo.png" # optional
#   googleAnalyticsUserID: "Your Analytics User Id" # optional
#
# permalinks:
#   post: "/:year/:month/:day/:title/"
...
